### ISSUE TITLE
Use the FFmpeg runtime

### ISSUE THREAD

**Issue by ricvelozo** [flathub/org.shotcut.Shotcut#11]
This app is taking too much space. Use the FFmpeg runtime like [org.blender.Blender](https://github.com/flathub/org.blender.Blender/pull/43); this will reduce the size by 57%.

**Comment by ricvelozo** [comment]
It may be necessary to create an extension like [flathub/org.blender.Blender!47](https://github.com/flathub/org.blender.Blender/pull/47) for H264 encoding.

**Comment by ddennedy** [comment]
Shotcut requires a build of the latest release of FFmpeg that also includes x264, x265, lame, FAAC, libvpx, Opus, Jack, PulseAudio, VA-API, and nvenc (via nv-codec-headers). (And possibly more in the future.) If the flathub FFmpeg runtime does not include these with extensions (or if the extensions do not install by default) I disagree. As the app's lead developer, consistency and thoroughness is more important than the space savings. I only support builds that I provide or approve (such as this one) because they offer an accepted combination of versions of dependencies.

**Comment by Erick555** [comment]
Those requirements rule out using ffmpeg from runtime. There may be still some reasoning behind using two ffmpegs: one without patented codecs bundled in app and one with patented codecs in extension. That will allow some vendors to preinstall Shotcut. This requires extra work and there may be not much demand for it though.

**Comment by yakushabb** [comment]
Freedesktop runtime 25.08 (and related runtimes GNOME 49, KDE 6.10, and KDE 5.15-25.08) provides FFMPEG.

The situation probably isn't going to change.

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/freedesktop-sdk-25.08.6/elements/components/ffmpeg.bst#L22
