### ISSUE TITLE
now that wayland is enabled for flatpaks, could we try to remove the x11 for ffmpeg call for harware acceleration

### ISSUE THREAD

**Issue by sudopluto** [flathub/org.shotcut.Shotcut#48]
have ffmpeg full and intel vaapi flatpaks installed, and the vainfo flatpak command looks good. tried to copy the ffmpeg call i saw in the log for detecting hardware encoder support into my base system (wayland w/ vaapi installed), and removing the connection_type=x11 from the ffmpeg call seemed promising

![image](https://user-images.githubusercontent.com/9754192/151274176-5d6b1278-f31d-4fcd-892d-d1a41ba70fc8.png)

**Comment by sudopluto** [comment]
i found this line in the source, if i change it to match above and build and test, what should i look for?
https://github.com/mltframework/shotcut/blob/af875d757ec593628c1b24b463523a3780058254/src/docks/encodedock.cpp#L2073

**Comment by ddennedy** [comment]
I need to review and test when `connection_type` is needed because I am not going to break X11 for wayland. A quick test shows it working fine. It was probably only needed for an older version of FFmpeg.
To test it, you need to remove two references to `connection_type` in that source code file. Then, export a file using a configured hardware encoder, right-click the export job and View > Log to look for anything suspicious. Finally, play back the video from beginning to end to se if it is OK.

**Comment by sudopluto** [comment]
ok, sounds good. i might try to just patch via flatpak and test from there using the sed command mentioned there, and test the flatpak both on a x11 session and a wayland one. if that works, ill put open a pr that people can use until your testing is over

**Comment by ddennedy** [comment]
All that is necessary is your positive test result. Otherwise, it is working for me in both detection and export without connection_type.
Here is where I added it into MLT: https://github.com/mltframework/mlt/commit/eb7540f3c8ce64ec5ba410d6bc807469cda0113c
And it refers to a source code file that had this change to iterate over all connection types:
https://github.com/FFmpeg/FFmpeg/commit/6b6b8a63713cf730a3793b7715be0470d6152191

My MLT change was only a few months after the FFmpeg change, and quite likely I was looking at a release version of FFmpeg at the time that did not yet include this FFmpeg change. So, I am willing to remove it from Shotcut next release in a few days if it works for you on wayland.

**Comment by sudopluto** [comment]
having trouble building the flatpak (a bit ironic now that i think about it),  so if i can't figure that out i'll do a regular build with the connection type stuff stripped. 

are avx / sse / openmp required? for some reason fftw fails to build for me out of the box, but if i remove them i get linking issues (i think) later on

**Comment by ddennedy** [comment]
test the build in #49 when it is ready

**Comment by sudopluto** [comment]
oh shoot didn't notice you opened a pr. but from my local build, both are working now with intel vaapi. here are the logs, didn't see anything suspicious 

[wayland-log.txt](https://github.com/flathub/org.shotcut.Shotcut/files/7947578/wayland-log.txt)
[x11-log.txt](https://github.com/flathub/org.shotcut.Shotcut/files/7947579/x11-log.txt)

both output videos look fine, and cpu graph during export shows that it's using the gpu

**Comment by ddennedy** [comment]
Thanks, I will close my PR since it was only for test, and leave yours open until the next release, which merges the change upstream!

**Comment by sudopluto** [comment]
cool. i noticed that the branch upstream missed out on the proxy encoder, i think that's the only other place that has the connection type flag

**Comment by ddennedy** [comment]
Yep thanks, got it now. Let me know if you want to help more on Shotcut and be paid for it by sending e-mail.

**Comment by sudopluto** [comment]
fixed on master in shotcut: https://github.com/mltframework/shotcut/commit/debaf54c6fa7a3c081a0a918812de8dbcdb7fda6
